CREATE FUNCTION [dbo].[ftn_Get_Numero](@Valor INT)
RETURNS NVARCHAR(30)
AS
BEGIN 
	DECLARE @RETORNO NVARCHAR(30)
	DECLARE @VALOR_STRING NVARCHAR(30)
	
	SET @VALOR_STRING = ( SELECT CONVERT(NVARCHAR, @Valor) )
	
	SET @RETORNO = (CASE WHEN LEN(@VALOR_STRING) > 6 THEN @VALOR_STRING ELSE RIGHT( '000000' + @VALOR_STRING, 6) END)
	
	RETURN @RETORNO
END