CREATE TABLE [dbo].[Clientes_Orig] (
    [cod_pais]                INT             NOT NULL,
    [razon_social]            VARCHAR (50)    NULL,
    [direccion]               VARCHAR (50)    NOT NULL,
    [telefono]                VARCHAR (15)    NOT NULL,
    [email]                   VARCHAR (30)    NOT NULL,
    [contacto]                VARCHAR (30)    NULL,
    [cedula_ruc]              VARCHAR (30)    NOT NULL,
    [nombre_comercial]        VARCHAR (50)    NULL,
    [cod_cliente]             VARCHAR (4)     NOT NULL,
    [nombres]                 VARCHAR (30)    NOT NULL,
    [apellidos]               VARCHAR (30)    NOT NULL,
    [consecutivo_usuario]     INT             NOT NULL,
    [consecutivo_usuario_ult] INT             NOT NULL,
    [dias_credito]            INT             NULL,
    [limite_credito]          NUMERIC (12, 2) NULL,
    [cod_sector_mercado]      INT             NOT NULL,
    [cod_vendedor]            INT             NOT NULL,
    [activo]                  BIT             NOT NULL,
    [cta_contable]            VARCHAR (25)    NOT NULL,
    [externo]                 BIT             NOT NULL,
    [excento_imp]             BIT             NOT NULL,
    [es_distribuidora]        BIT             NOT NULL,
    [cod_empresa]             INT             NOT NULL,
    CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED ([cod_pais] ASC, [cod_cliente] ASC, [externo] ASC, [cod_empresa] ASC)
);

