CREATE TABLE [dbo].[factura_det] (
    [cod_pais]                INT             NOT NULL,
    [cod_empresa]             INT             NOT NULL,
    [cod_puesto]              INT             NOT NULL,
    [no_factura]              INT             NOT NULL,
    [fecha]                   DATETIME        NOT NULL,
    [cod_producto]            VARCHAR (6)     NOT NULL,
    [consecutivo_usuario]     INT             NOT NULL,
    [consecutivo_usuario_ult] INT             NOT NULL,
    [porc_descuento]          DECIMAL (5, 2)  NOT NULL,
    [valor_descuento]         DECIMAL (12, 2) NOT NULL,
    [porc_iva]                DECIMAL (5, 2)  NOT NULL,
    [valor_iva]               DECIMAL (12, 2) NOT NULL,
    [anulada]                 BIT             NOT NULL,
    [fechaHora_anulacion]     DATETIME        NOT NULL,
    [sub_total]               DECIMAL (12, 2) NOT NULL,
    [neto]                    DECIMAL (12, 2) NOT NULL,
    [cantidad]                DECIMAL (12, 2) NOT NULL,
    [bultos]                  INT             NOT NULL,
    [cod_und_medida]          INT             NOT NULL,
    [precio_unidad]           DECIMAL (12, 2) NOT NULL,
    [desc_imprimir]           VARCHAR (25)    NOT NULL,
    CONSTRAINT [PK_factura_det] PRIMARY KEY CLUSTERED ([cod_pais] ASC, [cod_empresa] ASC, [cod_puesto] ASC, [no_factura] ASC, [fecha] ASC, [cod_producto] ASC)
);

